[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18.6"

[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npm run docs:build"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
