[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "18.6"

[build]
  publish = "docs/.vitepress/dist"
  command = "npm run docs:build"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
